name: Fitness_Community
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_timezone: ^1.0.6
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  flutter_calendar_carousel: ^2.4.2
  simple_circular_progress_bar: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.1.0
  url_launcher: ^6.0.0 
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  file_picker:
  flutter_local_notifications: ^8.2.0
  shared_preferences: ^2.2.3
  responsive_builder: ^0.7.0
  image_picker: ^1.0.8
  flutter_pdfview: ^1.3.2
  rive: ^0.8.0
  flutter_credit_card: ^4.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0
  cloud_firestore: ^4.17.5
  lottie: ^2.7.0
  animated_splash_screen: ^1.3.0
  get_it: ^7.6.7
  injectable:
  bloc: ^8.1.4
  build_runner: ^2.4.9
  either_dart: ^1.0.0
  responsive_sizer: ^3.3.1
  animate_do: ^3.3.4
  provider: ^6.1.2
  firebase_storage: ^11.6.0
  flutter_reaction_button: ^3.0.0+3
  another_flushbar: ^1.12.30
  permission_handler: ^11.0.1
  device_info_plus:
  page_transition:
  enefty_icons:
  google_fonts:
  dotted_line:
  rename_app: ^1.5.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/Beige and White Be Yourself Square Pillow (2).png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/font/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/font/Quicksand-Light.ttf
          weight: 300
        - asset: assets/font/Quicksand-Regular.ttf
        - asset: assets/font/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/font/Quicksand-Bold.ttf
          weight: 700
